FROM nginx:1.23

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone

# 安装字体库
#RUN apt-get update && \
#    apt-get install -y --no-install-recommends \
#    fontconfig \
#    fonts-dejavu-core \
#    fonts-dejavu-extra \
#    fonts-wqy-microhei \
#    fonts-wqy-zenhei \
#    libfreetype6 \
#    && rm -rf /var/lib/apt/lists/*

# 复制 Nginx 配置
COPY nginx-pc-admin.conf /etc/nginx/conf.d/default.conf

# 复制前端项目
COPY admin/ /usr/share/nginx/html/

# 暴露端口
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]