FROM nginx:1.23

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone

# 复制 Nginx 配置
COPY nginx-pc.conf /etc/nginx/conf.d/default.conf

# 复制前端项目
COPY pc/ /usr/share/nginx/html/pc/

# 暴露端口
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]